codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
        # advanced
        branches: null
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: false
    patch:
      default:
        # basic
        target: auto
        threshold: 10%
        base: auto
        # advanced
        branches: null
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no

ignore:
  - "tests/"
  - "scripts/"
  - "alembic/"
  - "**/__init__.py"
  - "**/__pycache__/"
  - "**/*.pyc"
